### ISSUE TITLE
Use JSON instead of CSV

### ISSUE THREAD

**Issue by amitness** [roshangm1/places-in-nepal#1]
Nice project. I think JSON will be a better format than CSV for this because the columns can vary according to places. That's why it's not rendering on GitHub.

In JSON, it could be something like

```json
{"Kathmandu, Nepal":[ "Ktm", "Kathmandu" ],
}
```

**Comment by roshangm1** [comment]
Hey @amitness. Thanks for the issue. I was working on a conversational app (bot) using API.AI.
In there, format for csv was like this. With json, it will be like:

 ```
       "value": "Kathmandu, Nepal",
        "synonyms": [
            "Kathmandu",
            "ktm"
        ]
    }
```
To make the data general for people and also specific for my project, I used the CSV format. Do you think, we can have in both formats ? JSON one converted from CSV one.

**Comment by amitness** [comment]
If that's the usecase, let's leave it as CSV. Just wanted to point it out because as you can see on Line 3 of CSV, there are 4 items but all other rows have 3 items. A standard CSV format should have equal number of columns for each row.

**Comment by roshangm1** [comment]
Sure @amitness . I got it.
